### PR TITLE
User serviceAccountName instead of serviceAccount

### PR DESCRIPTION
**Pull request by chmouel**
In the same spirit of https://github.com/tektoncd/pipeline/pull/1291 let use
serviceAccountName

/cc @vdemeester

### CODE REVIEW

**Review by vdemeester — COMMENTED** [review]
@chmouel shouldn't we run the script to update the yaml(s) ?

**Comment by chmouel** [comment]
It's done dynamically (via an hook mechanism), we don't add the serviceAccounts upstream since well it doesnt need it when running under vanilla kube,

**Comment by vdemeester** [comment]
@chmouel ah, gotcha

**Review by vdemeester — APPROVED** [review]
/lgtm

**Pull request merged**
