### PR TITLE
:robot: Triggering CI on branch 'release-next' after synching to upstream/master

### PR DESCRIPTION
**Pull request by alanfx**

### CODE REVIEW

**Comment by nikhil-thomas** [comment]
no code changes in https://github.com/openshift/pipelines-catalog or tektoncd/catalog.
retesting again. 
/retest 

also creating a dummy pr with break points to investigate https://github.com/openshift/tektoncd-catalog/pull/237

**Comment by alanfx** [comment]
OCF Webhook is merging this PR

**Pull request merged**
