### PR TITLE
Remove skipping the dotnet3 task in e2e

### PR DESCRIPTION
**Pull request by piyush-garg**
This will remove the skipping we have done for dotnet3
task as the image is now available in cluster.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

```
release-note
```

### CODE REVIEW

**Comment by piyush-garg** [comment]
Tested and verified by #273

**Comment by piyush-garg** [comment]
Ci passed, good to merge the PR @vdemeester @chmouel

**Comment by chmouel** [comment]
/lgtm
/approve

Thanks 👍🏼🔥

**Pull request merged**
