### PR TITLE
:robot: Triggering CI on branch 'release-next' after synching to upstream/master

### PR DESCRIPTION
**Pull request by alanfx**

### CODE REVIEW

**Comment by nikhil-thomas** [comment]
https://github.com/openshift/tektoncd-catalog/pull/239

**Comment by nikhil-thomas** [comment]
/retest
https://github.com/openshift/tektoncd-catalog/pull/239

**Comment by piyush-garg** [comment]
different task failed in all the three CI 

/retest

**Comment by piyush-garg** [comment]
s2i python 2 task is failing

**Comment by chmouel** [comment]
```
++ basename ./openshift/pipelines-catalog/LICENSE ./openshift/pipelines-catalog/OWNERS ./openshift/pipelines-catalog/README.md ./openshift/pipelines-catalog/openshift ./openshift/pipelines-catalog/task
basename: extra operand './openshift/pipelines-catalog/README.md'
```

🤔

**Comment by alanfx** [comment]
OCF Webhook is merging this PR

**Pull request merged**
